my:
  greeting: Hello World from config server
  list:
    values: One,Two,Three

db:
  connection: "{ConnectionString: 'http://___',userName: 'foo', password: 'pass'}"
  host: 127.0.0.1
  port: 1200
